mercure:
    hubs:
        default:
            url: '%env(default:mercure_default_url:MERCURE_URL)%'
            public_url: '%env(default:mercure_default_url:MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(default:mercure_default_secret:MERCURE_JWT_SECRET)%'
                publish: '*'
