twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['tailwind_2_layout.html.twig']
    globals:
        mercure_public_url: '%env(default::MERCURE_PUBLIC_URL)%'

when@test:
    twig:
        strict_variables: true
