CREATE TABLE formation_review_like (id INT AUTO_INCREMENT NOT NULL, vote SMALLINT NOT NULL, review_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_112A2D703E2E969B (review_id), INDEX IDX_112A2D70A76ED395 (user_id), UNIQUE INDEX uniq_review_like_user_review (review_id, user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 ENGINE = InnoDB;
ALTER TABLE formation_review_like ADD CONSTRAINT FK_112A2D703E2E969B FOREIGN KEY (review_id) REFERENCES formation_reviews (id) ON DELETE CASCADE;
ALTER TABLE formation_review_like ADD CONSTRAINT FK_112A2D70A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE formation_review_likes DROP FOREIGN KEY `FK_review_likes_review`;
ALTER TABLE formation_review_likes DROP FOREIGN KEY `FK_review_likes_user`;
DROP TABLE formation_review_likes;
ALTER TABLE passkey_credentials DROP FOREIGN KEY `FK_PASSKEY_USER`;
ALTER TABLE passkey_credentials CHANGE credential_id credential_id LONGTEXT NOT NULL, CHANGE public_key public_key LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE last_used_at last_used_at DATETIME DEFAULT NULL;
DROP INDEX idx_passkey_user ON passkey_credentials;
CREATE INDEX IDX_1D67AC5EA76ED395 ON passkey_credentials (user_id);
ALTER TABLE passkey_credentials ADD CONSTRAINT `FK_PASSKEY_USER` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE experiences DROP FOREIGN KEY `FK_82020E70CCFA12B8`;
DROP INDEX idx_experiences_profile_id ON experiences;
CREATE INDEX IDX_82020E70CCFA12B8 ON experiences (profile_id);
ALTER TABLE experiences ADD CONSTRAINT `FK_82020E70CCFA12B8` FOREIGN KEY (profile_id) REFERENCES profiles (id);
ALTER TABLE formation_enrollments DROP FOREIGN KEY `fk_enrollment_formation`;
ALTER TABLE formation_enrollments CHANGE enrolled_at enrolled_at DATETIME NOT NULL, CHANGE completed_at completed_at DATETIME DEFAULT NULL;
DROP INDEX fk_enrollment_formation ON formation_enrollments;
CREATE INDEX IDX_9325E1E95200282E ON formation_enrollments (formation_id);
ALTER TABLE formation_enrollments ADD CONSTRAINT `fk_enrollment_formation` FOREIGN KEY (formation_id) REFERENCES formations (id) ON DELETE CASCADE;
ALTER TABLE lesson_progress DROP FOREIGN KEY `lesson_progress_ibfk_1`;
DROP INDEX uq_lesson_progress ON lesson_progress;
ALTER TABLE lesson_progress DROP FOREIGN KEY `lesson_progress_ibfk_1`;
ALTER TABLE lesson_progress DROP FOREIGN KEY `lesson_progress_ibfk_2`;
ALTER TABLE lesson_progress DROP FOREIGN KEY `lesson_progress_ibfk_3`;
ALTER TABLE lesson_progress CHANGE completed completed TINYINT DEFAULT NULL, CHANGE progress_percentage progress_percentage NUMERIC(5, 2) DEFAULT NULL, CHANGE time_spent_minutes time_spent_minutes INT DEFAULT NULL, CHANGE last_accessed last_accessed DATETIME DEFAULT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL;
ALTER TABLE lesson_progress ADD CONSTRAINT FK_6A46B85F8F7DB25B FOREIGN KEY (enrollment_id) REFERENCES formation_enrollments (id) ON DELETE CASCADE;
DROP INDEX idx_lp_enrollment ON lesson_progress;
CREATE INDEX IDX_6A46B85F8F7DB25B ON lesson_progress (enrollment_id);
DROP INDEX module_id ON lesson_progress;
CREATE INDEX IDX_6A46B85FAFC2B591 ON lesson_progress (module_id);
DROP INDEX idx_lp_user ON lesson_progress;
CREATE INDEX IDX_6A46B85FA76ED395 ON lesson_progress (user_id);
ALTER TABLE lesson_progress ADD CONSTRAINT `lesson_progress_ibfk_1` FOREIGN KEY (enrollment_id) REFERENCES enrollments (id) ON DELETE CASCADE;
ALTER TABLE lesson_progress ADD CONSTRAINT `lesson_progress_ibfk_2` FOREIGN KEY (module_id) REFERENCES formation_modules (id) ON DELETE CASCADE;
ALTER TABLE lesson_progress ADD CONSTRAINT `lesson_progress_ibfk_3` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE post_likes DROP FOREIGN KEY `FK_post_likes_post`;
ALTER TABLE post_likes DROP FOREIGN KEY `post_likes_ibfk_2`;
ALTER TABLE post_likes CHANGE created_date created_date DATETIME NOT NULL;
DROP INDEX idx_post_likes_post ON post_likes;
CREATE INDEX IDX_DED1C2924B89032C ON post_likes (post_id);
DROP INDEX user_id ON post_likes;
CREATE INDEX IDX_DED1C292A76ED395 ON post_likes (user_id);
DROP INDEX uq_post_like ON post_likes;
CREATE UNIQUE INDEX unique_user_post_like ON post_likes (post_id, user_id);
ALTER TABLE post_likes ADD CONSTRAINT `FK_post_likes_post` FOREIGN KEY (post_id) REFERENCES community_posts (id) ON DELETE CASCADE;
ALTER TABLE post_likes ADD CONSTRAINT `post_likes_ibfk_2` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE support_tickets DROP FOREIGN KEY `support_tickets_ibfk_2`;
DROP INDEX idx_tickets_assigned ON support_tickets;
DROP INDEX idx_tickets_status ON support_tickets;
DROP INDEX idx_tickets_priority ON support_tickets;
ALTER TABLE support_tickets DROP FOREIGN KEY `support_tickets_ibfk_1`;
ALTER TABLE support_tickets CHANGE priority priority VARCHAR(20) NOT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE created_date created_date DATETIME NOT NULL, CHANGE updated_date updated_date DATETIME DEFAULT NULL;
DROP INDEX idx_tickets_user ON support_tickets;
CREATE INDEX IDX_E9739508A76ED395 ON support_tickets (user_id);
ALTER TABLE support_tickets ADD CONSTRAINT `support_tickets_ibfk_1` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
DROP INDEX username ON users;
DROP INDEX idx_users_email ON users;
ALTER TABLE users CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE password password VARCHAR(255) DEFAULT NULL, CHANGE role role VARCHAR(50) DEFAULT NULL, CHANGE full_name full_name VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE is_verified is_verified TINYINT DEFAULT 0 NOT NULL, CHANGE is_active is_active TINYINT DEFAULT 1 NOT NULL, CHANGE two_factor_enabled two_factor_enabled TINYINT DEFAULT 0 NOT NULL, CHANGE terms_accepted terms_accepted TINYINT DEFAULT 0 NOT NULL;
ALTER TABLE formation_modules DROP FOREIGN KEY `formation_modules_ibfk_1`;
ALTER TABLE formation_modules CHANGE description description LONGTEXT DEFAULT NULL, CHANGE content_url content_url LONGTEXT DEFAULT NULL, CHANGE duration_minutes duration_minutes INT DEFAULT NULL, CHANGE order_index order_index INT DEFAULT NULL, CHANGE content content LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL;
DROP INDEX formation_id ON formation_modules;
CREATE INDEX IDX_6B4806AC5200282E ON formation_modules (formation_id);
ALTER TABLE formation_modules ADD CONSTRAINT `formation_modules_ibfk_1` FOREIGN KEY (formation_id) REFERENCES formations (id) ON DELETE CASCADE;
ALTER TABLE skills DROP FOREIGN KEY `skills_ibfk_1`;
ALTER TABLE skills DROP FOREIGN KEY `skills_ibfk_1`;
ALTER TABLE skills ADD CONSTRAINT FK_D5311670CCFA12B8 FOREIGN KEY (profile_id) REFERENCES profiles (id);
DROP INDEX idx_skills_profile_id ON skills;
CREATE INDEX IDX_D5311670CCFA12B8 ON skills (profile_id);
ALTER TABLE skills ADD CONSTRAINT `skills_ibfk_1` FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE;
ALTER TABLE group_members DROP FOREIGN KEY `group_members_ibfk_1`;
ALTER TABLE group_members DROP FOREIGN KEY `group_members_ibfk_2`;
ALTER TABLE group_members CHANGE role role VARCHAR(20) NOT NULL, CHANGE joined_date joined_date DATETIME NOT NULL;
DROP INDEX idx_group_members_group ON group_members;
CREATE INDEX IDX_C3A086F3FE54D947 ON group_members (group_id);
DROP INDEX idx_group_members_user ON group_members;
CREATE INDEX IDX_C3A086F3A76ED395 ON group_members (user_id);
DROP INDEX uq_group_member ON group_members;
CREATE UNIQUE INDEX unique_group_user ON group_members (group_id, user_id);
ALTER TABLE group_members ADD CONSTRAINT `group_members_ibfk_1` FOREIGN KEY (group_id) REFERENCES community_groups (id) ON DELETE CASCADE;
ALTER TABLE group_members ADD CONSTRAINT `group_members_ibfk_2` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE login_history DROP FOREIGN KEY `FK_37976E36A76ED395`;
ALTER TABLE login_history CHANGE user_id user_id INT NOT NULL, CHANGE ip ip VARCHAR(45) DEFAULT NULL, CHANGE user_agent user_agent LONGTEXT DEFAULT NULL, CHANGE method method VARCHAR(50) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
DROP INDEX idx_37976e36a76ed395 ON login_history;
CREATE INDEX idx_login_history_user ON login_history (user_id);
ALTER TABLE login_history ADD CONSTRAINT `FK_37976E36A76ED395` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE ticket_messages DROP FOREIGN KEY `ticket_messages_ibfk_2`;
DROP INDEX sender_id ON ticket_messages;
ALTER TABLE ticket_messages DROP FOREIGN KEY `ticket_messages_ibfk_1`;
ALTER TABLE ticket_messages CHANGE sender_id sender_id INT DEFAULT NULL, CHANGE message message LONGTEXT DEFAULT NULL, CHANGE is_internal is_internal TINYINT DEFAULT NULL, CHANGE created_date created_date DATETIME NOT NULL, CHANGE attachments_json attachments_json LONGTEXT DEFAULT NULL, CHANGE audio_path audio_path LONGTEXT DEFAULT NULL, CHANGE is_audio is_audio TINYINT DEFAULT NULL;
DROP INDEX idx_ticket_messages_ticket ON ticket_messages;
CREATE INDEX IDX_5E6BE217700047D2 ON ticket_messages (ticket_id);
ALTER TABLE ticket_messages ADD CONSTRAINT `ticket_messages_ibfk_1` FOREIGN KEY (ticket_id) REFERENCES support_tickets (id) ON DELETE CASCADE;
ALTER TABLE formation_reviews DROP FOREIGN KEY `FK_formation_reviews_formation`;
ALTER TABLE formation_reviews DROP FOREIGN KEY `FK_formation_reviews_user`;
ALTER TABLE formation_reviews CHANGE created_at created_at DATETIME NOT NULL;
DROP INDEX idx_formation_reviews_formation ON formation_reviews;
CREATE INDEX IDX_2C8FAE745200282E ON formation_reviews (formation_id);
DROP INDEX fk_formation_reviews_user ON formation_reviews;
CREATE INDEX IDX_2C8FAE74A76ED395 ON formation_reviews (user_id);
ALTER TABLE formation_reviews ADD CONSTRAINT `FK_formation_reviews_formation` FOREIGN KEY (formation_id) REFERENCES formations (id) ON DELETE CASCADE;
ALTER TABLE formation_reviews ADD CONSTRAINT `FK_formation_reviews_user` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE profiles DROP FOREIGN KEY `profiles_ibfk_1`;
ALTER TABLE profiles DROP FOREIGN KEY `profiles_ibfk_1`;
ALTER TABLE profiles CHANGE cv_url cv_url LONGTEXT DEFAULT NULL, CHANGE bio bio LONGTEXT DEFAULT NULL;
ALTER TABLE profiles ADD CONSTRAINT FK_8B308530A76ED395 FOREIGN KEY (user_id) REFERENCES users (id);
DROP INDEX idx_profiles_user_id ON profiles;
CREATE INDEX IDX_8B308530A76ED395 ON profiles (user_id);
ALTER TABLE profiles ADD CONSTRAINT `profiles_ibfk_1` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE wallets DROP FOREIGN KEY `FK_WALLET_USER`;
ALTER TABLE wallets CHANGE currency currency VARCHAR(10) DEFAULT 'CONNECTS' NOT NULL;
DROP INDEX uniq_wallet_user ON wallets;
CREATE UNIQUE INDEX UNIQ_967AAA6CA76ED395 ON wallets (user_id);
ALTER TABLE wallets ADD CONSTRAINT `FK_WALLET_USER` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE payment_transactions DROP FOREIGN KEY `payment_transactions_ibfk_1`;
ALTER TABLE payment_transactions DROP FOREIGN KEY `payment_transactions_ibfk_2`;
ALTER TABLE payment_transactions DROP FOREIGN KEY `payment_transactions_ibfk_3`;
ALTER TABLE payment_transactions CHANGE amount amount NUMERIC(12, 2) DEFAULT NULL, CHANGE currency currency VARCHAR(10) DEFAULT NULL, CHANGE transaction_type transaction_type VARCHAR(30) DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT NULL, CHANGE transaction_date transaction_date DATETIME DEFAULT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL;
DROP INDEX idx_transactions_payslip ON payment_transactions;
CREATE INDEX IDX_8C58AD56296F5EA7 ON payment_transactions (payslip_id);
DROP INDEX from_account_id ON payment_transactions;
CREATE INDEX IDX_8C58AD56B0CF99BD ON payment_transactions (from_account_id);
DROP INDEX to_account_id ON payment_transactions;
CREATE INDEX IDX_8C58AD56BC58BDC7 ON payment_transactions (to_account_id);
ALTER TABLE payment_transactions ADD CONSTRAINT `payment_transactions_ibfk_1` FOREIGN KEY (payslip_id) REFERENCES payslips (id) ON DELETE SET NULL;
ALTER TABLE payment_transactions ADD CONSTRAINT `payment_transactions_ibfk_2` FOREIGN KEY (from_account_id) REFERENCES bank_accounts (id) ON DELETE SET NULL;
ALTER TABLE payment_transactions ADD CONSTRAINT `payment_transactions_ibfk_3` FOREIGN KEY (to_account_id) REFERENCES bank_accounts (id) ON DELETE SET NULL;
ALTER TABLE bonuses DROP FOREIGN KEY `FK_bonuses_contract`;
ALTER TABLE bonuses CHANGE amount amount NUMERIC(10, 2) DEFAULT NULL;
DROP INDEX idx_bonuses_contract ON bonuses;
CREATE INDEX IDX_8535CFD22576E0FD ON bonuses (contract_id);
ALTER TABLE bonuses ADD CONSTRAINT `FK_bonuses_contract` FOREIGN KEY (contract_id) REFERENCES contracts (id) ON DELETE SET NULL;
ALTER TABLE job_reviews DROP FOREIGN KEY `FK_JR_CONTRACT`;
ALTER TABLE job_reviews CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE job_reviews ADD CONSTRAINT FK_F39F5C94F675F31B FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE job_reviews ADD CONSTRAINT FK_F39F5C94158E0B66 FOREIGN KEY (target_id) REFERENCES users (id) ON DELETE CASCADE;
CREATE INDEX IDX_F39F5C94F675F31B ON job_reviews (author_id);
DROP INDEX idx_job_reviews_contract ON job_reviews;
CREATE INDEX IDX_F39F5C942576E0FD ON job_reviews (contract_id);
DROP INDEX idx_job_reviews_target ON job_reviews;
CREATE INDEX IDX_F39F5C94158E0B66 ON job_reviews (target_id);
ALTER TABLE job_reviews ADD CONSTRAINT `FK_JR_CONTRACT` FOREIGN KEY (contract_id) REFERENCES contracts (id) ON DELETE CASCADE;
ALTER TABLE invoices DROP FOREIGN KEY `FK_invoices_company`;
ALTER TABLE invoices DROP FOREIGN KEY `FK_invoices_contract`;
ALTER TABLE invoices DROP FOREIGN KEY `FK_invoices_freelancer`;
ALTER TABLE invoices CHANGE amount amount NUMERIC(12, 2) DEFAULT NULL, CHANGE currency currency VARCHAR(10) DEFAULT NULL, CHANGE status status VARCHAR(20) NOT NULL, CHANGE issued_date issued_date DATETIME DEFAULT NULL;
DROP INDEX invoice_number ON invoices;
CREATE UNIQUE INDEX UNIQ_6A2F2F952DA68207 ON invoices (invoice_number);
DROP INDEX idx_invoices_contract ON invoices;
CREATE INDEX IDX_6A2F2F952576E0FD ON invoices (contract_id);
DROP INDEX idx_invoices_freelancer ON invoices;
CREATE INDEX IDX_6A2F2F958545BDF5 ON invoices (freelancer_id);
DROP INDEX idx_invoices_company ON invoices;
CREATE INDEX IDX_6A2F2F95979B1AD6 ON invoices (company_id);
ALTER TABLE invoices ADD CONSTRAINT `FK_invoices_company` FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE SET NULL;
ALTER TABLE invoices ADD CONSTRAINT `FK_invoices_contract` FOREIGN KEY (contract_id) REFERENCES contracts (id) ON DELETE CASCADE;
ALTER TABLE invoices ADD CONSTRAINT `FK_invoices_freelancer` FOREIGN KEY (freelancer_id) REFERENCES users (id);
ALTER TABLE escrow_accounts DROP FOREIGN KEY `FK_escrow_employer`;
ALTER TABLE escrow_accounts DROP FOREIGN KEY `FK_escrow_freelancer`;
ALTER TABLE escrow_accounts DROP FOREIGN KEY `FK_escrow_employer`;
ALTER TABLE escrow_accounts DROP FOREIGN KEY `FK_escrow_freelancer`;
ALTER TABLE escrow_accounts CHANGE amount amount NUMERIC(12, 2) DEFAULT NULL, CHANGE created_date created_date DATETIME NOT NULL;
ALTER TABLE escrow_accounts ADD CONSTRAINT FK_9E94F49741CD9E7A FOREIGN KEY (employer_id) REFERENCES users (id);
ALTER TABLE escrow_accounts ADD CONSTRAINT FK_9E94F4978545BDF5 FOREIGN KEY (freelancer_id) REFERENCES users (id);
DROP INDEX fk_escrow_employer ON escrow_accounts;
CREATE INDEX IDX_9E94F49741CD9E7A ON escrow_accounts (employer_id);
DROP INDEX fk_escrow_freelancer ON escrow_accounts;
CREATE INDEX IDX_9E94F4978545BDF5 ON escrow_accounts (freelancer_id);
ALTER TABLE escrow_accounts ADD CONSTRAINT `FK_escrow_employer` FOREIGN KEY (employer_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE escrow_accounts ADD CONSTRAINT `FK_escrow_freelancer` FOREIGN KEY (freelancer_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE payslips DROP FOREIGN KEY `payslips_ibfk_1`;
DROP INDEX idx_payslips_contract ON payslips;
DROP INDEX uq_payslip_contract_period ON payslips;
DROP INDEX uq_payslip_period ON payslips;
DROP INDEX idx_payslips_period ON payslips;
ALTER TABLE payslips DROP FOREIGN KEY `payslips_ibfk_2`;
ALTER TABLE payslips DROP contract_id, DROP period_month, DROP period_year, DROP gross_salary, DROP net_salary, DROP cnss_employee, DROP cnss_employer, DROP irpp, DROP payment_status, DROP payment_date, DROP pdf_url, DROP created_date, CHANGE other_deductions other_deductions NUMERIC(10, 2) DEFAULT NULL, CHANGE bonuses bonuses NUMERIC(10, 2) DEFAULT NULL, CHANGE currency currency VARCHAR(10) DEFAULT NULL, CHANGE base_salary base_salary NUMERIC(10, 2) DEFAULT NULL, CHANGE overtime_hours overtime_hours NUMERIC(10, 2) DEFAULT NULL, CHANGE overtime_total overtime_total NUMERIC(10, 2) DEFAULT NULL, CHANGE status status VARCHAR(50) DEFAULT NULL, CHANGE deductions_json deductions_json LONGTEXT DEFAULT NULL, CHANGE bonuses_json bonuses_json LONGTEXT DEFAULT NULL;
DROP INDEX idx_payslips_user ON payslips;
CREATE INDEX IDX_A6292EDAA76ED395 ON payslips (user_id);
ALTER TABLE payslips ADD CONSTRAINT `payslips_ibfk_2` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE contracts DROP FOREIGN KEY `FK_950A973BD7CCBD6`;
DROP INDEX IDX_950A973BD7CCBD6 ON contracts;
ALTER TABLE contracts DROP FOREIGN KEY `FK_contracts_hire_offer`;
ALTER TABLE contracts CHANGE salary salary NUMERIC(10, 2) DEFAULT NULL, CHANGE company_Name company_id INT NOT NULL;
ALTER TABLE contracts ADD CONSTRAINT FK_950A973979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id);
CREATE INDEX IDX_950A973979B1AD6 ON contracts (company_id);
DROP INDEX idx_contracts_hire_offer ON contracts;
CREATE INDEX IDX_950A973E4F0180E ON contracts (hire_offer_id);
ALTER TABLE contracts ADD CONSTRAINT `FK_contracts_hire_offer` FOREIGN KEY (hire_offer_id) REFERENCES hire_offers (id) ON DELETE SET NULL;
ALTER TABLE quiz_questions DROP FOREIGN KEY `quiz_questions_ibfk_1`;
ALTER TABLE quiz_questions CHANGE question_text question_text LONGTEXT NOT NULL, CHANGE correct_option correct_option VARCHAR(1) NOT NULL, CHANGE points points INT DEFAULT NULL, CHANGE order_index order_index INT DEFAULT NULL;
DROP INDEX quiz_id ON quiz_questions;
CREATE INDEX IDX_8CBC2533853CD175 ON quiz_questions (quiz_id);
ALTER TABLE quiz_questions ADD CONSTRAINT `quiz_questions_ibfk_1` FOREIGN KEY (quiz_id) REFERENCES quizzes (id) ON DELETE CASCADE;
ALTER TABLE ticket_attachments DROP FOREIGN KEY `ticket_attachments_ibfk_2`;
ALTER TABLE ticket_attachments DROP FOREIGN KEY `ticket_attachments_ibfk_1`;
ALTER TABLE ticket_attachments DROP FOREIGN KEY `ticket_attachments_ibfk_2`;
ALTER TABLE ticket_attachments CHANGE file_path file_path LONGTEXT NOT NULL, CHANGE created_date created_date DATETIME NOT NULL;
ALTER TABLE ticket_attachments ADD CONSTRAINT FK_2B54FCA9537A1329 FOREIGN KEY (message_id) REFERENCES ticket_messages (id) ON DELETE SET NULL;
DROP INDEX idx_ticket_attachments_ticket ON ticket_attachments;
CREATE INDEX IDX_2B54FCA9700047D2 ON ticket_attachments (ticket_id);
DROP INDEX idx_ticket_attachments_message ON ticket_attachments;
CREATE INDEX IDX_2B54FCA9537A1329 ON ticket_attachments (message_id);
ALTER TABLE ticket_attachments ADD CONSTRAINT `ticket_attachments_ibfk_1` FOREIGN KEY (ticket_id) REFERENCES support_tickets (id) ON DELETE CASCADE;
ALTER TABLE ticket_attachments ADD CONSTRAINT `ticket_attachments_ibfk_2` FOREIGN KEY (message_id) REFERENCES ticket_messages (id) ON DELETE CASCADE;
ALTER TABLE portfolio_items DROP FOREIGN KEY `portfolio_items_ibfk_1`;
ALTER TABLE portfolio_items DROP FOREIGN KEY `portfolio_items_ibfk_1`;
ALTER TABLE portfolio_items CHANGE title title VARCHAR(200) DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE project_url project_url LONGTEXT DEFAULT NULL, CHANGE image_url image_url LONGTEXT DEFAULT NULL, CHANGE created_date created_date DATETIME NOT NULL;
ALTER TABLE portfolio_items ADD CONSTRAINT FK_BC46C308A76ED395 FOREIGN KEY (user_id) REFERENCES users (id);
DROP INDEX idx_portfolio_user ON portfolio_items;
CREATE INDEX IDX_BC46C308A76ED395 ON portfolio_items (user_id);
ALTER TABLE portfolio_items ADD CONSTRAINT `portfolio_items_ibfk_1` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE formation_materials DROP FOREIGN KEY `formation_materials_ibfk_2`;
DROP INDEX uploaded_by ON formation_materials;
ALTER TABLE formation_materials DROP FOREIGN KEY `formation_materials_ibfk_1`;
ALTER TABLE formation_materials CHANGE description description LONGTEXT DEFAULT NULL, CHANGE file_url file_url LONGTEXT DEFAULT NULL, CHANGE file_size file_size BIGINT DEFAULT NULL, CHANGE download_count download_count INT DEFAULT NULL, CHANGE created_date created_date DATETIME NOT NULL, CHANGE uploaded_by uploaded_by_id INT DEFAULT NULL;
ALTER TABLE formation_materials ADD CONSTRAINT FK_516A4668A2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL;
CREATE INDEX IDX_516A4668A2B28FE8 ON formation_materials (uploaded_by_id);
DROP INDEX idx_fmat_formation ON formation_materials;
CREATE INDEX IDX_516A46685200282E ON formation_materials (formation_id);
ALTER TABLE formation_materials ADD CONSTRAINT `formation_materials_ibfk_1` FOREIGN KEY (formation_id) REFERENCES formations (id) ON DELETE CASCADE;
ALTER TABLE formations DROP FOREIGN KEY `formations_ibfk_1`;
DROP INDEX created_by ON formations;
DROP INDEX idx_formations_category ON formations;
DROP INDEX idx_formations_status ON formations;
ALTER TABLE formations ADD updated_by INT DEFAULT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE category category VARCHAR(64) NOT NULL, CHANGE duration_hours duration_hours INT DEFAULT NULL, CHANGE cost cost NUMERIC(10, 2) DEFAULT NULL, CHANGE currency currency VARCHAR(10) DEFAULT NULL, CHANGE provider provider VARCHAR(255) DEFAULT NULL, CHANGE image_url image_url LONGTEXT DEFAULT NULL, CHANGE level level VARCHAR(32) DEFAULT NULL, CHANGE is_free is_free TINYINT DEFAULT NULL, CHANGE created_date created_date DATETIME NOT NULL, CHANGE status status VARCHAR(20) DEFAULT NULL, CHANGE lesson_count lesson_count INT DEFAULT NULL, CHANGE director_signature director_signature LONGTEXT DEFAULT NULL, CHANGE updated_date updated_date DATETIME DEFAULT NULL;
ALTER TABLE member_invitations DROP FOREIGN KEY `fk_inv_invitee`;
ALTER TABLE member_invitations DROP FOREIGN KEY `fk_inv_inviter`;
ALTER TABLE member_invitations CHANGE status status VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL;
DROP INDEX fk_inv_inviter ON member_invitations;
CREATE INDEX IDX_FA1A046CB79F4F04 ON member_invitations (inviter_id);
DROP INDEX fk_inv_invitee ON member_invitations;
CREATE INDEX IDX_FA1A046C7A512022 ON member_invitations (invitee_id);
ALTER TABLE member_invitations ADD CONSTRAINT `fk_inv_invitee` FOREIGN KEY (invitee_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE member_invitations ADD CONSTRAINT `fk_inv_inviter` FOREIGN KEY (inviter_id) REFERENCES users (id) ON DELETE CASCADE;
DROP INDEX idx_notif_read ON notifications;
ALTER TABLE notifications DROP FOREIGN KEY `notifications_ibfk_1`;
ALTER TABLE notifications CHANGE user_id user_id INT DEFAULT NULL, CHANGE type type VARCHAR(50) NOT NULL, CHANGE message message LONGTEXT DEFAULT NULL, CHANGE icon icon VARCHAR(10) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL;
DROP INDEX idx_notif_user ON notifications;
CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id);
ALTER TABLE notifications ADD CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_feedback DROP FOREIGN KEY `user_feedback_ibfk_1`;
ALTER TABLE user_feedback CHANGE feedback_type feedback_type VARCHAR(255) DEFAULT NULL, CHANGE rating rating INT DEFAULT NULL, CHANGE comment comment LONGTEXT DEFAULT NULL, CHANGE category category VARCHAR(255) DEFAULT NULL, CHANGE is_resolved is_resolved TINYINT DEFAULT NULL, CHANGE created_date created_date DATETIME NOT NULL, CHANGE ticket_id ticket_id INT NOT NULL;
ALTER TABLE user_feedback ADD CONSTRAINT FK_32A4A058700047D2 FOREIGN KEY (ticket_id) REFERENCES support_tickets (id) ON DELETE CASCADE;
CREATE INDEX IDX_32A4A058700047D2 ON user_feedback (ticket_id);
DROP INDEX idx_feedback_user ON user_feedback;
CREATE INDEX IDX_32A4A058A76ED395 ON user_feedback (user_id);
ALTER TABLE user_feedback ADD CONSTRAINT `user_feedback_ibfk_1` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE post_comments DROP FOREIGN KEY `FK_post_comments_post`;
ALTER TABLE post_comments DROP FOREIGN KEY `post_comments_ibfk_2`;
ALTER TABLE post_comments CHANGE content content LONGTEXT NOT NULL, CHANGE created_date created_date DATETIME NOT NULL;
DROP INDEX idx_post_comments_post ON post_comments;
CREATE INDEX IDX_E0731F8B4B89032C ON post_comments (post_id);
DROP INDEX author_id ON post_comments;
CREATE INDEX IDX_E0731F8BF675F31B ON post_comments (author_id);
ALTER TABLE post_comments ADD CONSTRAINT `FK_post_comments_post` FOREIGN KEY (post_id) REFERENCES community_posts (id) ON DELETE CASCADE;
ALTER TABLE post_comments ADD CONSTRAINT `post_comments_ibfk_2` FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE quiz_results DROP FOREIGN KEY `quiz_results_ibfk_1`;
ALTER TABLE quiz_results DROP FOREIGN KEY `quiz_results_ibfk_2`;
ALTER TABLE quiz_results CHANGE score score INT DEFAULT NULL, CHANGE max_score max_score INT DEFAULT NULL, CHANGE passed passed TINYINT DEFAULT NULL, CHANGE attempt_number attempt_number INT DEFAULT NULL, CHANGE taken_date taken_date DATETIME DEFAULT NULL, CHANGE time_spent_seconds time_spent_seconds INT DEFAULT NULL;
DROP INDEX idx_quiz_results_quiz ON quiz_results;
CREATE INDEX IDX_8DF949B4853CD175 ON quiz_results (quiz_id);
DROP INDEX idx_quiz_results_user ON quiz_results;
CREATE INDEX IDX_8DF949B4A76ED395 ON quiz_results (user_id);
ALTER TABLE quiz_results ADD CONSTRAINT `quiz_results_ibfk_1` FOREIGN KEY (quiz_id) REFERENCES quizzes (id) ON DELETE CASCADE;
ALTER TABLE quiz_results ADD CONSTRAINT `quiz_results_ibfk_2` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_sessions DROP FOREIGN KEY `FK_8849CBDEA76ED395`;
ALTER TABLE user_sessions CHANGE session_id session_id VARCHAR(128) DEFAULT NULL, CHANGE ip ip VARCHAR(45) DEFAULT NULL, CHANGE user_agent user_agent LONGTEXT DEFAULT NULL, CHANGE last_activity last_activity DATETIME NOT NULL, CHANGE created_at created_at DATETIME NOT NULL;
DROP INDEX uniq_8849cbde613fecdf ON user_sessions;
CREATE UNIQUE INDEX UNIQ_7AED7913613FECDF ON user_sessions (session_id);
DROP INDEX idx_8849cbdea76ed395 ON user_sessions;
CREATE INDEX idx_user_sessions_user ON user_sessions (user_id);
ALTER TABLE user_sessions ADD CONSTRAINT `FK_8849CBDEA76ED395` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE quizzes DROP FOREIGN KEY `quizzes_ibfk_2`;
ALTER TABLE quizzes DROP FOREIGN KEY `quizzes_ibfk_1`;
ALTER TABLE quizzes DROP FOREIGN KEY `quizzes_ibfk_2`;
ALTER TABLE quizzes CHANGE description description LONGTEXT DEFAULT NULL, CHANGE pass_score pass_score INT DEFAULT NULL, CHANGE max_attempts max_attempts INT DEFAULT NULL, CHANGE time_limit_minutes time_limit_minutes INT DEFAULT NULL;
ALTER TABLE quizzes ADD CONSTRAINT FK_94DC9FB5AFC2B591 FOREIGN KEY (module_id) REFERENCES formation_modules (id) ON DELETE CASCADE;
DROP INDEX formation_id ON quizzes;
CREATE INDEX IDX_94DC9FB55200282E ON quizzes (formation_id);
DROP INDEX module_id ON quizzes;
CREATE INDEX IDX_94DC9FB5AFC2B591 ON quizzes (module_id);
ALTER TABLE quizzes ADD CONSTRAINT `quizzes_ibfk_1` FOREIGN KEY (formation_id) REFERENCES formations (id) ON DELETE CASCADE;
ALTER TABLE quizzes ADD CONSTRAINT `quizzes_ibfk_2` FOREIGN KEY (module_id) REFERENCES formation_modules (id) ON DELETE SET NULL;
ALTER TABLE interviews DROP INDEX idx_interviews_application, ADD UNIQUE INDEX UNIQ_3A7526823E030ACD (application_id);
DROP INDEX idx_interviews_status ON interviews;
DROP INDEX idx_interviews_date ON interviews;
ALTER TABLE interviews DROP interview_format, DROP interview_date, DROP interview_status, CHANGE scheduled_date scheduled_date DATETIME DEFAULT NULL, CHANGE duration_minutes duration_minutes INT DEFAULT NULL, CHANGE type type VARCHAR(20) DEFAULT 'ONLINE' NOT NULL, CHANGE location location VARCHAR(150) DEFAULT NULL, CHANGE video_link video_link VARCHAR(500) DEFAULT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT 'SCHEDULED' NOT NULL, CHANGE feedback feedback LONGTEXT DEFAULT NULL, CHANGE rating rating INT DEFAULT NULL, CHANGE timezone timezone VARCHAR(50) DEFAULT NULL, CHANGE created_date created_date DATETIME NOT NULL;
ALTER TABLE job_offers DROP FOREIGN KEY `job_offers_ibfk_1`;
DROP INDEX idx_job_offers_status ON job_offers;
DROP INDEX ft_job_search ON job_offers;
ALTER TABLE job_offers DROP FOREIGN KEY `job_offers_ibfk_1`;
ALTER TABLE job_offers CHANGE description description LONGTEXT DEFAULT NULL, CHANGE requirements requirements LONGTEXT DEFAULT NULL, CHANGE currency currency VARCHAR(10) DEFAULT 'EUR' NOT NULL, CHANGE posted_date posted_date DATETIME DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT 'OPEN' NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE skills_required skills_required LONGTEXT DEFAULT NULL, CHANGE benefits benefits LONGTEXT DEFAULT NULL, CHANGE is_featured is_featured TINYINT DEFAULT 0 NOT NULL, CHANGE views_count views_count INT DEFAULT 0 NOT NULL, CHANGE applications_count applications_count INT DEFAULT 0 NOT NULL, CHANGE expires_at expires_at DATETIME DEFAULT NULL;
ALTER TABLE job_offers ADD CONSTRAINT FK_8A4229A6979B1AD6 FOREIGN KEY (company_id) REFERENCES companies (id);
DROP INDEX idx_job_offers_company_id ON job_offers;
CREATE INDEX IDX_8A4229A6979B1AD6 ON job_offers (company_id);
ALTER TABLE job_offers ADD CONSTRAINT `job_offers_ibfk_1` FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE;
ALTER TABLE job_preferences DROP FOREIGN KEY `job_preferences_ibfk_1`;
ALTER TABLE job_preferences CHANGE preferred_currency preferred_currency VARCHAR(10) DEFAULT NULL, CHANGE is_remote_ok is_remote_ok TINYINT DEFAULT NULL, CHANGE created_date created_date DATETIME NOT NULL, CHANGE updated_date updated_date DATETIME DEFAULT NULL;
DROP INDEX uq_job_pref_user ON job_preferences;
CREATE UNIQUE INDEX UNIQ_8A5DBDBCA76ED395 ON job_preferences (user_id);
ALTER TABLE job_preferences ADD CONSTRAINT `job_preferences_ibfk_1` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
DROP INDEX idx_hire_offers_status ON hire_offers;
ALTER TABLE hire_offers DROP FOREIGN KEY `hire_offers_ibfk_1`;
ALTER TABLE hire_offers CHANGE currency currency VARCHAR(10) DEFAULT NULL, CHANGE contract_type contract_type VARCHAR(20) DEFAULT NULL, CHANGE benefits benefits LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT NULL, CHANGE created_date created_date DATETIME NOT NULL;
DROP INDEX idx_hire_offers_application ON hire_offers;
CREATE INDEX IDX_5425907D3E030ACD ON hire_offers (application_id);
ALTER TABLE hire_offers ADD CONSTRAINT `hire_offers_ibfk_1` FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE;
DROP INDEX uq_saved_jobs_user_url ON saved_jobs;
DROP INDEX idx_saved_jobs_user_time ON saved_jobs;
ALTER TABLE saved_jobs CHANGE job_url job_url LONGTEXT NOT NULL, CHANGE saved_at saved_at DATETIME NOT NULL;
