controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

recruitment_controllers:
    resource:
        path: ../src/Recruitment/Controller/
        namespace: App\Recruitment\Controller
    type: attribute
